name = "logiledger"
compatibility_date = "2026-05-03"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "logiledger-db"
database_id = "8aac259e-c962-42ef-82ac-cd6192e0993c"
migrations_dir = "migrations"
